apiVersion: apps/v1
kind: Deployment
metadata:
  name: converter-service-deployment
spec:
  selector:
    matchLabels:
      app: converter-service
  template:
    metadata:
      labels:
        app: converter-service
    spec:
      containers:
      - name: converter-service
        image: sanjogpariyar2024/video-to-mp3-converterservice:latest
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        envFrom:
          - configMapRef:
              name: converter-configmap
        ports:
          - containerPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: converter-service
spec:
  selector:
    app: converter-service
  ports:
  - port: 7000
    targetPort: 7000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: converter-configmap
data:
  MONGO_URL: mongodb://root:example@mongo-service:27017
  RABBITMQ_URL: amqp://guest:guest@rabbitmq-service:5672/
